# Site settings
title: Curiosity Motive
email: curiositymotive@gmail.com
description: > # Curiosity Motive needs a description.
url: "http://curiositymotive.github.io" # the base hostname & protocol for your site
enable_retina: true
exclude: ["node_modules", "gulpfile.js", "package.json"]
nav_list:
  Home : ['Home', '/', 'fa-circle-o']
  About : ['About', '/about', 'fa-circle-o']
  Contact : ['Contact', '/contact', 'fa-circle-o']
single_footer: '<p>&copy; 2017 Curiosity Motive</p>'
footer_links:
  About: ['About', '/about']
  Writer: ['CM', '/about']
gems:
  - jekyll-gist
permalink: /:title/

# Build settings
markdown: kramdown
