version: '2'
services:
  web:
    build: .
    command: bash -c "gulp"
    volumes:
      - .:/curiositymotive
      - /curiositymotive/node_modules
    ports:
      - 3000:3000
      - 3001:3001
